<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Motorbike already rented at this period' => 'Мотоцикл занят в указанный период',
    'Motorbike already rented by another user' => 'Мотоцикл арендован другим пользователем',
    'Motorbike not found' => 'Мотоцикл не найден',
    'Period is incorrect, can\'t check is motorbike already rented by another user or not' => 'Не удалось проверить занятость мотоцикла другим пользователем, т.к. период указан некорректно',
    'Period is incorrect, can\'t check is motorbike already rented at this period or not' => 'Не удалось проверить занятость мотоцикла на указанный период, т.к. период указан некорректно',
];
